apiVersion: v1
kind: Pod
metadata:
  labels:
    run: log
  name: log-foo
spec:
  containers:
    - image: poneding/hello-app:v3
      name: foo
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
