apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-scheduler-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-scheduler-controller
subjects:
- kind: ServiceAccount
  name: my-scheduler-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: my-scheduler-extender
    tier: control-plane
  name: my-scheduler-extender
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: my-scheduler-controller
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: my-scheduler-controller
        tier: control-plane
    spec:
      serviceAccountName: my-scheduler-controller
      containers:
      - image: poneding/my-kube-scheduler-controller:v1.0
        name: my-scheduler-controller
        imagePullPolicy: Always